Performance Model (WIP)
bensander/Tensile pull request #1
Opened 2020-03-17 03:14 UTC by amdkila

*Done*
- Created PerformanceReporter that writes PeakGFlops, Efficiency, and L2MemBandwidth to stdout

*TODO*
- Add command line arguments such as L2WriteHits
- Figure out how to call reporter in library code
- Cleanup

2020-03-27 14:32 UTC, bensander requested changes

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/lib/source/ContractionSolution.cpp
> +        int frequency = std::stoi(getOutputCmd("/opt/rocm/bin/rocm-smi --showclocks -d 0 | grep sclk | awk {\'print $7\'} | tr -d \'(Mhz)\'"));
can we use the SMI API here?  @sdquiring may be able to provide a pointer.

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/lib/source/ContractionSolution.cpp
> +        double NumCUs = std::stod(getOutputCmd("/opt/rocm/bin/rocminfo | grep Compute | awk \'FNR == 2 {print $3}\'"));
we can get this from multiprocessorCount in hipGetDeviceProperties

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/lib/source/ContractionSolution.cpp
> +        spm.memReadBytesA = (NumBatches*M*N*K)/MT1 * readMultiplier;//(problemType.aType == DataType::Float ? 4 : 2); // hack
please remove the old hacky code (no need to retain in comments)

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/lib/source/ContractionSolution.cpp
> +        double readMultiplier = 2;//m_ReadMultiplier, PerformanceReporter;
what is readMultiplier supposed to represent?  Perhaps this is bytes per element based on data-type - if so let's give it a better name.  Also Scott had a suggestion for how to determine this programmatically w/o need for hard-coding.

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/client/include/LogReporter.hpp
> +                                         L2BandwidthMBps, AluUs, MemReadUs, MemWriteUs,
I had used empty as a separator so can easily find the GFLOPs in output
Do we need to print PeakFGLOps on each row - I think just the efficiency would be fine.  Cols are at a premium.
What is L2BandwidthMBps?

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/client/include/LogReporter.hpp
> +                                         MemGlobalWrites, MemWriteBytes,
What is difference MemGlobalReads vs MemReadBytes ?   I think we only need one.

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/client/source/PerformanceReporter.cpp
> +        }
remove, just rely on a user-provided parm for this

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/client/source/BenchmarkTimer.cpp
> +            m_reporter->report(ResultKey::MemGlobalWrites, pp.staticModel.memGlobalWrites);
the comment referred to a future feature where we use rocprof APIs to read memory bandwidth performance counters and compare those against the values predicted by the model.  I think these new counters are something different - not sure they are needed

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/lib/source/ContractionSolution.cpp
> +        double flops = readMultiplier*NumBatches*M*N*K;
this should still be "2" - we can remove readMultiplier.  Flops are always 2X since we could add and mul for each computation.

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/lib/source/ContractionSolution.cpp
>          double beta = 0.0; // TODO-model - base on input value
@amdkila @squiring - can we access the runtime beta value here?  Beta impacts the dynamic code paths in the kernel and runtime and thus the bandwidth that the kernel consumes.

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/lib/source/ContractionSolution.cpp
> +        spm.memReadBytesC = (NumBatches*M*N) * betaReads * cInfo.elementSize;
@amdkila  - remove #if 0 code now that you have something that replaces it

2020-03-27 14:32 UTC, bensander commented on Tensile/Source/client/source/PerformanceReporter.cpp
> +            if(key == ResultKey::ClockRateSys && m_deviceProps)
reportValue_double seems an odd place to if-check the key and record clocks in member vars like m_memClockMhz- should be done in a constructor or elsewhere?

2020-03-27 15:40 UTC, amdkila commented on Tensile/Source/lib/source/ContractionSolution.cpp
> +        double readMultiplier = 2;//m_ReadMultiplier, PerformanceReporter;
It is supposed to represent bytes per element based on data type- I will change that. Some of these comments are referring to outdated commits. I'm determining this based on the problem type- the code for this is in PerformanceReporter.cpp, and then I'm passing it to the library code.

2020-03-27 16:14 UTC, amdkila commented on Tensile/Source/client/include/LogReporter.hpp
> +                                         L2BandwidthMBps, AluUs, MemReadUs, MemWriteUs,
I'll re-add the empty column and remove all values here except Efficiency. My understanding is that L2BandwidthMBps is readMultiplier * memoryBandwidthMBps, with readMultiplier being the number of values that can be read from a 64 bit register assuming we're packing all the values. Based on your comments, it seems like I'm not correct.

2020-03-27 19:47 UTC, sdquiring commented on Tensile/Source/client/source/PerformanceReporter.cpp
> +        {
Most of the code should be in this unified function.  The other `reportValue` functions should **just** call this one.

2020-03-27 19:47 UTC, sdquiring commented on Tensile/Source/client/include/LogReporter.hpp
> +                                         L2BandwidthMBps, AluUs, MemReadUs, MemWriteUs,
If we want to make the output nicer, we should add a new Reporter class that writes values that don't change run-to-run, but prints them between Problems.

2020-03-28 18:56 UTC, bensander approved these changes

2020-03-28 18:56 UTC, merged